version: "3.9"

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "${REDIS_EXTERNAL_PORT}:${REDIS_PORT}"
    restart: unless-stopped
    networks:
      - chat-network
    env_file:
      - .env

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - chat-network
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_LOG_RETENTION_HOURS: 168
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - chat-network
    restart: unless-stopped

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      DYNAMIC_CONFIG_ENABLED: 'true'
    networks:
      - chat-network
    restart: unless-stopped

  auth_service:
    build: ./auth_service
    container_name: auth_service
    ports:
      - "${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}"
      - "5677:5677"
    volumes:
      - ./auth_service:/app
    env_file:
      - .env
    depends_on:
      - auth_postgres
      - redis
      - kafka
    restart: unless-stopped
    command: >
      sh -c "pip install -r requirements.txt &&
             python3 manage.py makemigrations &&
             python3 manage.py migrate &&
             if [ \"$DEBUG_MODE\" = \"true\" ]; then
                python3 -m debugpy --listen 0.0.0.0:5677 --wait-for-client manage.py runserver 0.0.0.0:${AUTH_SERVICE_PORT};
             else
                python3 manage.py runserver 0.0.0.0:${AUTH_SERVICE_PORT};
             fi"
    networks:
      - chat-network

  chat_service:
    build: ./chat_service
    container_name: chat_service
    ports:
      - "${CHAT_SERVICE_PORT}:${CHAT_SERVICE_PORT}"
      - "5678:5678"
    expose:
      - "${CHAT_SERVICE_PORT}"
    volumes:
      - ./chat_service:/app
    env_file:
      - .env
    depends_on:
      - chat_postgres
      - redis
      - kafka
      - auth_service
    restart: unless-stopped
    command: >
      sh -c "pip install -r requirements.txt &&
             python3 manage.py makemigrations &&
             python3 manage.py migrate &&
             if [ \"$DEBUG_MODE\" = \"true\" ]; then
                python3 -m debugpy --listen 0.0.0.0:5678 --wait-for-client -m daphne -b 0.0.0.0 -p ${CHAT_SERVICE_PORT} chat_service.asgi:application;
             else
                daphne -b 0.0.0.0 -p ${CHAT_SERVICE_PORT} chat_service.asgi:application;
             fi"
    networks:
      - chat-network

  celery:
    build: ./auth_service
    container_name: celery
    depends_on:
      - redis
    volumes:
      - ./auth_service:/app
    env_file:
      - .env
    restart: unless-stopped
    command: >
      sh -c "pip install -r requirements.txt &&
              celery -A auth_service.celery worker --loglevel=info"
    networks:
      - chat-network

  auth-kafka-consumer:
    build: ./auth_service
    container_name: auth-kafka-consumer
    depends_on:
      - kafka
      - auth_postgres
    volumes:
      - ./auth_service:/app
    env_file:
      - .env
    restart: unless-stopped
    command: >
      sh -c "pip install -r requirements.txt &&
             python3 manage.py migrate &&
             python3 manage.py start_kafka_consumer"
    networks:
      - chat-network

  chat-kafka-consumer:
    build: ./chat_service
    container_name: chat-kafka-consumer
    depends_on:
      - kafka
      - chat_postgres
    volumes:
      - ./chat_service:/app
    env_file:
      - .env
    restart: unless-stopped
    command: >
      sh -c "pip install -r requirements.txt &&
             python3 manage.py migrate &&
             python3 manage.py start_kafka_consumer"
    networks:
      - chat-network

  auth_postgres:
    image: postgres:15
    container_name: auth_postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${AUTH_SERVICE_POSTGRES_USER}
      - POSTGRES_PASSWORD=${AUTH_SERVICE_POSTGRES_PASSWORD}
      - POSTGRES_DB=${AUTH_SERVICE_POSTGRES_DB}
    ports:
      - "${AUTH_POSTGRES_EXTERNAL_PORT}:5432"
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - chat-network

  chat_postgres:
    image: postgres:15
    container_name: chat_postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${CHAT_SERVICE_POSTGRES_USER}
      - POSTGRES_PASSWORD=${CHAT_SERVICE_POSTGRES_PASSWORD}
      - POSTGRES_DB=${CHAT_SERVICE_POSTGRES_DB}
    ports:
      - "${CHAT_POSTGRES_EXTERNAL_PORT}:5432"
    volumes:
      - chat_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - chat-network

volumes:
  auth_postgres_data:
  chat_postgres_data:
  kafka_data:

networks:
  chat-network:
    driver: bridge
#  python3 manage.py runserver 0.0.0.0:${AUTH_SERVICE_PORT}"
#  python3 manage.py runserver 0.0.0.0:${CHAT_SERVICE_PORT}"
