# Generated by Django 5.2.5 on 2025-09-14 05:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender', models.UUIDField(help_text='Reference to User ID from auth service')),
                ('content', models.TextField(blank=True, null=True)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('file', 'File')], default='text', max_length=20)),
                ('file_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('mentions', models.JSONField(blank=True, default=list, help_text="List of mentioned users uuid's")),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.UUIDField(help_text='Reference to User ID from auth service')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('seen', 'Seen')], default='sent', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomMembers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.UUIDField(help_text='Reference to User ID from auth service')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_members', models.IntegerField(default=100)),
                ('is_private', models.BooleanField(default=False)),
                ('allow_file_sharing', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.UUIDField(help_text='Reference to User ID from auth service')),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_typing', models.BooleanField(default=False)),
                ('typing_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_avatar',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['created_by', '-created_at'], name='chat_app_ro_created_acebcf_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['is_group', '-updated_at'], name='chat_app_ro_is_grou_614566_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['created_at'], name='chat_app_ro_created_1d5951_idx'),
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_app.room'),
        ),
        migrations.AddField(
            model_name='messagestatus',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_app.message'),
        ),
        migrations.AddField(
            model_name='roommembers',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_app.room'),
        ),
        migrations.AddField(
            model_name='roomsettings',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='chat_app.room'),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_app.room'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['room', '-created_at'], name='chat_app_me_room_id_1ccca9_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', '-created_at'], name='chat_app_me_sender_11c8bf_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['room', 'is_deleted', '-created_at'], name='chat_app_me_room_id_71081d_idx'),
        ),
        migrations.AddIndex(
            model_name='messagestatus',
            index=models.Index(fields=['message', 'user'], name='chat_app_me_message_1c83c4_idx'),
        ),
        migrations.AddIndex(
            model_name='messagestatus',
            index=models.Index(fields=['user', 'status'], name='chat_app_me_user_c43272_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messagestatus',
            unique_together={('message', 'user')},
        ),
        migrations.AddIndex(
            model_name='roommembers',
            index=models.Index(fields=['user', 'room'], name='chat_app_ro_user_70f6b2_idx'),
        ),
        migrations.AddIndex(
            model_name='roommembers',
            index=models.Index(fields=['room', 'role'], name='chat_app_ro_room_id_390ad3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='roommembers',
            unique_together={('room', 'user')},
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['room', 'last_seen'], name='chat_app_us_room_id_b56db4_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['user', 'is_typing'], name='chat_app_us_user_2ad648_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='useractivity',
            unique_together={('user', 'room')},
        ),
    ]
