# Generated by Django 5.2.5 on 2025-09-17 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_message_messagestatus_roommembers_roomsettings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommembers',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roommembers', to='chat_app.room'),
        ),
    ]
