# Generated by Django 5.2.5 on 2025-09-21 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0003_alter_roommembers_room'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='Message_room_id_0a64b5_idx',
            old_name='chat_app_me_room_id_1ccca9_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='Message_sender_896f10_idx',
            old_name='chat_app_me_sender_11c8bf_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='Message_room_id_be9d36_idx',
            old_name='chat_app_me_room_id_71081d_idx',
        ),
        migrations.RenameIndex(
            model_name='messagestatus',
            new_name='MessageStat_message_a0c1be_idx',
            old_name='chat_app_me_message_1c83c4_idx',
        ),
        migrations.RenameIndex(
            model_name='messagestatus',
            new_name='MessageStat_user_a97265_idx',
            old_name='chat_app_me_user_c43272_idx',
        ),
        migrations.RenameIndex(
            model_name='room',
            new_name='Room_created_7ee068_idx',
            old_name='chat_app_ro_created_acebcf_idx',
        ),
        migrations.RenameIndex(
            model_name='room',
            new_name='Room_is_grou_10367e_idx',
            old_name='chat_app_ro_is_grou_614566_idx',
        ),
        migrations.RenameIndex(
            model_name='room',
            new_name='Room_created_10b3d6_idx',
            old_name='chat_app_ro_created_1d5951_idx',
        ),
        migrations.RenameIndex(
            model_name='roommembers',
            new_name='RoomMember_user_f1d52d_idx',
            old_name='chat_app_ro_user_70f6b2_idx',
        ),
        migrations.RenameIndex(
            model_name='roommembers',
            new_name='RoomMember_room_id_4c277b_idx',
            old_name='chat_app_ro_room_id_390ad3_idx',
        ),
        migrations.RenameIndex(
            model_name='useractivity',
            new_name='UserActivit_room_id_33d413_idx',
            old_name='chat_app_us_room_id_b56db4_idx',
        ),
        migrations.RenameIndex(
            model_name='useractivity',
            new_name='UserActivit_user_490935_idx',
            old_name='chat_app_us_user_2ad648_idx',
        ),
        migrations.AlterModelTable(
            name='message',
            table='Message',
        ),
        migrations.AlterModelTable(
            name='messagestatus',
            table='MessageStatus',
        ),
        migrations.AlterModelTable(
            name='room',
            table='Room',
        ),
        migrations.AlterModelTable(
            name='roommembers',
            table='RoomMember',
        ),
        migrations.AlterModelTable(
            name='useractivity',
            table='UserActivity',
        ),
    ]
