# Generated by Django 5.2.5 on 2025-09-21 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0004_rename_chat_app_me_room_id_1ccca9_idx_message_room_id_0a64b5_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='roomsettings',
            table='RoomSettings',
        ),
    ]
